## Workflow for My Mechanic Shop

name: My Mechanic Shop Workflow

on:
  push:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Create virtual environment
        run: |
          python -m venv venv

      - name: Install dependencies
        run: |
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r requirements.txt

      - name: Show installed packages
        run: |
          ./venv/bin/pip freeze

      - name: Print debugging information
        run: |
          echo "Python Version: $(./venv/bin/python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

      - name: Run tests
        env:
          FLASK_ENV: testing
          SECRET_KEY: dev_secret_key
        run: |
          ./venv/bin/python -m unittest discover -s tests -p 'test_*.py'

deploy:
  needs: test
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Create virtual environment
      run: |
        python -m venv venv

    - name: Install dependencies
      run: |
        ./venv/bin/pip install --upgrade pip
        ./venv/bin/pip install -r requirements.txt

    - name: Deploy API
      uses: johnbeynon/render-deploy@v1
      with:
        service_key: ${{ secrets.SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}