## Workflow for My Mechanic Shop

name: My Mechanic Shop Workflow

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - bame: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Create virtual enviroment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install --upgrade pip 

    - name: Print debugging information
      run: |
        echo 'Python Version: $(python --version)'
        echo 'Working Directory: $(pwd)'
        echo 'Contents of Working Directory: $(ls -l)'
        echo 'Contents of site-packages: $(ls -l venv/lib/python*/site-packages)'

## ------- Pipelines -------

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      
      - name: Create virtual enviroment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install --upgrade pip

      - name: Run tests
        run : python -m unittest discover -s test -p 'test_*.py'